# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
      - ./stock_main.sql:/docker-entrypoint-initdb.d/stock_main.sql
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - ./mariadb.cnf:/etc/mysql/mariadb.cnf

    environment:
      MYSQL_ROOT_PASSWORD: 111111
      TZ: Asia/Taipei

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    db_vol:
