# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
      - ./stock_main.sql:/docker-entrypoint-initdb.d/stock_main.sql
      - ./mariadb.cnf:/etc/mysql/mariadb.cnf

    environment:
      MYSQL_ROOT_PASSWORD: 111111
      TZ: Asia/Taipei

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  https:
    image: steveltn/https-portal
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
        DOMAINS: 'example.com -> http://example.com:8080'
        PRODUCTION: 'true'
        FORCE_RENEW: 'true'
    volumes:
    - /data/ssl_certs:/var/lib/https-portal

volumes:
    db_vol:
