#!/bin/bash
#start db and admin
# docker-compose -f docker-compose.yml up
#use admin
# http://localhost:8080/ 用yml資料登入 (root/111111)
#stop 
# docker-compose stop
#rm
# docker-compose rm
#find volume
# docker volume ls 
# docker volume inspect <volume name>
