# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      TZ: Asia/Taipei

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    db_vol:
